### PR TITLE
Find free xvfb display instead of hardcoded 99 using the -a option

### LINKED ISSUE #772: node-firefox often fails with "Error: cannot open display: :99"
## Meta -

Image(s):  
node-firefox

Docker-Selenium Image Version(s):  
3.14.0-arsenic and previous versions

Docker Version:  
17.06.2-ce

OS: 
Debian 3.16.43-2 (2017-04-30)

Setup:
wdio + grid with a hub, 8 chrome nodes and 8 firefox nodes.
Tests run on a Jenkins slave

## Expected Behavior -

All nodes work as expected throughout the duration of the test run.

## Actual Behavior -

Sporadically, one (sometimes more) firefox nodes fail to have a session initiated, leading to the spec assigned to that session not being executed and the whole . The error is:

```
[33mselenium-firefox-1_1  |[0m Failed to connect to Mir: Failed to connect to server socket: No such file or directory
[33mselenium-firefox-1_1  |[0m Unable to init server: Could not connect: Connection refused
[33mselenium-firefox-1_1  |[0m Error: cannot open display: :99
[32;1mui-test_1             |[0m ERROR: Process unexpectedly closed with status 1
[32;1mui-test_1             |[0m Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
[32;1mui-test_1             |[0m System info: host: '2eb130e13a7b', ip: '172.19.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-4-amd64', java.version: '1.8.0_171'
[32;1mui-test_1             |[0m Driver info: driver.version: unknown
[32;1mui-test_1             |[0m remote stacktrace: 
[32;1mui-test_1             |[0m firefox
[32;1mui-test_1             |[0m     at new RuntimeError (/home/xxx/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
[32;1mui-test_1             |[0m     at Request._callback (/home/xxx/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
[32;1mui-test_1             |[0m     at Request.self.callback (/home/xxx/node_modules/webdriverio/node_modules/request/request.js:186:22)
[32;1mui-test_1             |[0m     at emitTwo (events.js:126:13)
[32;1mui-test_1             |[0m     at Request.emit (events.js:214:7)
[32;1mui-test_1             |[0m     at Request.<anonymous> (/home/xxx/node_modules/webdriverio/node_modules/request/request.js:1163:10)
[32;1mui-test_1             |[0m     at emitOne (events.js:116:13)
[32;1mui-test_1             |[0m     at Request.emit (events.js:211:7)
[32;1mui-test_1             |[0m     at IncomingMessage.<anonymous> (/home/xxx/node_modules/webdriverio/node_modules/request/request.js:1085:12)
[32;1mui-test_1             |[0m     at Object.onceWrapper (events.js:313:30)
```

### PR DESCRIPTION
**Pull request by anto-ac**
Up until now the xvfb display has been hardcoded to 99 for all nodes.
This sometimes causes errors if the display is not actually free.
xvfb-run has a -a --auto-servernum option, which tries to get a free
server number, starting at 99, or the argument to --server-num.

Fixes #772

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

File: NodeBase/Dockerfile [hunk 1]
```diff
@@ -79,17 +79,13 @@ USER seluser
 #==============================
 # Scripts to run Selenium Node
 #==============================
-COPY entry_point.sh \
-  functions.sh \
-    /opt/bin/
-
+COPY entry_point.sh  /opt/bin/
```
Comment (diemol) [inline NodeBase/Dockerfile]: There is no need to update this file, please revert the changes ->
```
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: DO *NOT* EDIT THIS FILE.  IT IS GENERATED.
# PLEASE UPDATE Dockerfile.txt INSTEAD OF THIS FILE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

File: tests/test-shell-functions.sh [hunk 2]
```diff
@@ -9,7 +9,6 @@ if [ "$(uname)" != 'Darwin' ] ; then
     echo "Could not find 'bats'. Please install it first, e.g., following https://github.com/sstephenson/bats#installing-bats-from-source."
     exit 1
   fi
-  NodeBase/test-functions.sh || exit 1
```
Comment (diemol) [inline tests/test-shell-functions.sh]: We should remove this file as well, also from the Makefile.

File: NodeDebug/entry_point.sh [hunk 3]
```diff
@@ -68,6 +64,10 @@ NODE_PID=$!
 trap shutdown SIGTERM SIGINT
 for i in $(seq 1 10)
 do
+  DISPLAY=$(xvfb-run printenv DISPLAY)
+  if [ -z "$DISPLAY" ]; then
+    break
```
Comment (diemol) [inline NodeDebug/entry_point.sh]: Could we add an "echo" here, mentioning that the DISPLAY env var was not found?

File: StandaloneDebug/entry_point.sh [hunk 4]
```diff
@@ -24,17 +22,18 @@ fi
...
   java ${JAVA_OPTS} -jar /opt/selenium/selenium-server-standalone.jar \
   ${SE_OPTS} &
 NODE_PID=$!
 
 trap shutdown SIGTERM SIGINT
 for i in $(seq 1 10)
 do
+  DISPLAY=$(xvfb-run printenv DISPLAY)
+  if [ -z "$DISPLAY" ]; then
+    break
```
Comment (diemol) [inline StandaloneDebug/entry_point.sh]: Could we add an "echo" here, mentioning that the DISPLAY env var was not found?

**Comment by diemol** [comment]
Thanks @anto-ac! I added some comments to it.

File: NodeBase/Dockerfile (hunk 1 above)
Comment (anto-ac) [reply NodeBase/Dockerfile]: Sorry, I don't know how I missed this!
